"""Complete DPDP Act 2023 + DPDP Rules 2025 obligation registry for Data Fiduciaries."""

from __future__ import annotations

from typing import Any, TypedDict


class ObligationDef(TypedDict):
    id: str
    title: str
    category: str
    act_sections: list[str]
    rule_references: list[str]
    deadline: str
    priority: int
    description: str


# All substantive Data Fiduciary obligations under DPDP Act 2023 and Rules 2025.
OBLIGATIONS: list[ObligationDef] = [
    # --- Lawful processing ---
    {
        "id": "scope_digital_personal_data",
        "title": "Processing of digital personal data within scope",
        "category": "Lawful processing",
        "act_sections": ["Section 3"],
        "rule_references": [],
        "deadline": "2027-05-13",
        "priority": 1,
        "description": "Act applies to digital personal data processed in India or offered goods/services to persons in India.",
    },
    {
        "id": "lawful_basis_consent",
        "title": "Lawful basis — valid consent for processing",
        "category": "Lawful processing",
        "act_sections": ["Section 4", "Section 6"],
        "rule_references": ["Rule 3", "Rule 4"],
        "deadline": "2027-05-13",
        "priority": 1,
        "description": "Personal data processed only for lawful purpose with free, specific, informed, unambiguous consent.",
    },
    {
        "id": "lawful_basis_legitimate_use",
        "title": "Lawful basis — legitimate uses (if relied upon)",
        "category": "Lawful processing",
        "act_sections": ["Section 7"],
        "rule_references": ["Rule 5"],
        "deadline": "2027-05-13",
        "priority": 2,
        "description": "Certain processing permitted without consent (voluntary provision, state functions, employment, emergencies).",
    },
    {
        "id": "purpose_limitation",
        "title": "Purpose limitation",
        "category": "Lawful processing",
        "act_sections": ["Section 4(1)", "Section 6(1)"],
        "rule_references": ["Rule 3"],
        "deadline": "2027-05-13",
        "priority": 1,
        "description": "Data processed only for purpose consented to or permitted under legitimate use.",
    },
    # --- Notice & consent ---
    {
        "id": "notice_to_principal",
        "title": "Notice to Data Principal before consent",
        "category": "Notice & consent",
        "act_sections": ["Section 5"],
        "rule_references": ["Rule 3"],
        "deadline": "2027-05-13",
        "priority": 1,
        "description": "Clear notice covering data collected, purpose, rights, grievance contact, and withdrawal.",
    },
    {
        "id": "notice_required_elements",
        "title": "Notice contains all required elements (Rule 3)",
        "category": "Notice & consent",
        "act_sections": ["Section 5"],
        "rule_references": ["Rule 3"],
        "deadline": "2027-05-13",
        "priority": 1,
        "description": "Notice must include specific data, purposes, goods/services provided, withdrawal, rights, and Board complaint route.",
    },
    {
        "id": "consent_specific_informed",
        "title": "Consent is free, specific, informed, and unambiguous",
        "category": "Notice & consent",
        "act_sections": ["Section 6(1)"],
        "rule_references": ["Rule 4"],
        "deadline": "2027-05-13",
        "priority": 1,
        "description": "Consent obtained through clear affirmative action; not bundled or implied.",
    },
    {
        "id": "consent_records",
        "title": "Consent records maintained",
        "category": "Notice & consent",
        "act_sections": ["Section 6"],
        "rule_references": ["Rule 4"],
        "deadline": "2027-05-13",
        "priority": 2,
        "description": "Ability to demonstrate when and how consent was given.",
    },
    {
        "id": "consent_withdrawal",
        "title": "Consent withdrawal as easy as giving consent",
        "category": "Notice & consent",
        "act_sections": ["Section 6(4)"],
        "rule_references": ["Rule 3", "Rule 4"],
        "deadline": "2027-05-13",
        "priority": 1,
        "description": "Withdrawal mechanism at least as accessible as consent; downstream processors notified.",
    },
    {
        "id": "consent_manager_readiness",
        "title": "Consent Manager provisions readiness",
        "category": "Notice & consent",
        "act_sections": ["Section 6(9)"],
        "rule_references": ["Rule 4"],
        "deadline": "2026-11-13",
        "priority": 2,
        "description": "Consent Manager framework effective Nov 2026; assess integration if applicable.",
    },
    # --- Data quality & lifecycle ---
    {
        "id": "data_accuracy",
        "title": "Reasonable efforts to ensure data accuracy and completeness",
        "category": "Data quality & lifecycle",
        "act_sections": ["Section 8(3)"],
        "rule_references": [],
        "deadline": "2027-05-13",
        "priority": 2,
        "description": "Data Fiduciary must make reasonable efforts to ensure personal data is accurate and complete.",
    },
    {
        "id": "retention_erasure",
        "title": "Data retention limits and erasure when purpose ends",
        "category": "Data quality & lifecycle",
        "act_sections": ["Section 8(4)", "Section 12"],
        "rule_references": ["Rule 5", "Third Schedule"],
        "deadline": "2027-05-13",
        "priority": 1,
        "description": "Erase data when purpose served, consent withdrawn, or erasure requested; follow Third Schedule timelines.",
    },
    {
        "id": "erasure_pre_notification",
        "title": "Pre-erasure notification to Data Principal (48 hours)",
        "category": "Data quality & lifecycle",
        "act_sections": ["Section 8(7)"],
        "rule_references": ["Rule 5"],
        "deadline": "2027-05-13",
        "priority": 3,
        "description": "Notify Data Principal at least 48 hours before deletion under Third Schedule unless they act to continue purpose.",
    },
    {
        "id": "deletion_on_withdrawal",
        "title": "Deletion upon consent withdrawal",
        "category": "Data quality & lifecycle",
        "act_sections": ["Section 6(4)", "Section 8(4)"],
        "rule_references": ["Rule 4", "Rule 5"],
        "deadline": "2027-05-13",
        "priority": 1,
        "description": "Cease processing and erase data within reasonable time after consent withdrawal.",
    },
    # --- Data Principal rights ---
    {
        "id": "right_of_access",
        "title": "Right of access — summary of personal data and processing",
        "category": "Data Principal rights",
        "act_sections": ["Section 11"],
        "rule_references": ["Rule 8", "Rule 9"],
        "deadline": "2027-05-13",
        "priority": 2,
        "description": "Data Principal may obtain summary of personal data and processing activities.",
    },
    {
        "id": "right_of_correction",
        "title": "Right of correction and updating of personal data",
        "category": "Data Principal rights",
        "act_sections": ["Section 12"],
        "rule_references": ["Rule 8"],
        "deadline": "2027-05-13",
        "priority": 2,
        "description": "Process to correct inaccurate or misleading personal data.",
    },
    {
        "id": "right_of_erasure",
        "title": "Right of erasure",
        "category": "Data Principal rights",
        "act_sections": ["Section 13"],
        "rule_references": ["Rule 8"],
        "deadline": "2027-05-13",
        "priority": 2,
        "description": "Process to erase personal data when consent withdrawn or no longer necessary.",
    },
    {
        "id": "right_of_grievance",
        "title": "Right of grievance redressal",
        "category": "Data Principal rights",
        "act_sections": ["Section 14"],
        "rule_references": ["Rule 9"],
        "deadline": "2027-05-13",
        "priority": 1,
        "description": "Grievance mechanism responding within reasonable time (Rules: up to 90 days).",
    },
    {
        "id": "right_of_nomination",
        "title": "Right of nomination",
        "category": "Data Principal rights",
        "act_sections": ["Section 15"],
        "rule_references": ["Rule 9"],
        "deadline": "2027-05-13",
        "priority": 3,
        "description": "Data Principal may nominate another individual to exercise rights in event of death or incapacity.",
    },
    {
        "id": "rights_request_verification",
        "title": "Identity verification for rights requests",
        "category": "Data Principal rights",
        "act_sections": ["Section 11", "Section 12", "Section 13"],
        "rule_references": ["Rule 8", "Rule 9"],
        "deadline": "2027-05-13",
        "priority": 2,
        "description": "Published method and identifiers required to verify Data Principal before fulfilling requests.",
    },
    {
        "id": "rights_response_timeline",
        "title": "Rights requests handled within reasonable timelines",
        "category": "Data Principal rights",
        "act_sections": ["Section 11", "Section 12", "Section 13", "Section 14"],
        "rule_references": ["Rule 8", "Rule 9"],
        "deadline": "2027-05-13",
        "priority": 2,
        "description": "Documented timelines for access, correction, erasure, and grievance responses.",
    },
    # --- Transparency & contact ---
    {
        "id": "contact_publication",
        "title": "Publication of business contact / DPO details",
        "category": "Transparency & contact",
        "act_sections": ["Section 8(9)"],
        "rule_references": ["Rule 9", "Rule 14"],
        "deadline": "2027-05-13",
        "priority": 1,
        "description": "Display contact of DPO or authorised person on website/app for data processing queries.",
    },
    {
        "id": "grievance_officer_appointed",
        "title": "Grievance officer appointed and contact published",
        "category": "Transparency & contact",
        "act_sections": ["Section 8(9)", "Section 14"],
        "rule_references": ["Rule 9"],
        "deadline": "2027-05-13",
        "priority": 1,
        "description": "Grievance redressal system published on website/app.",
    },
    # --- Processors & transfers ---
    {
        "id": "processor_contracts",
        "title": "Written contract with Data Processors",
        "category": "Processors & transfers",
        "act_sections": ["Section 8(2)"],
        "rule_references": ["Rule 6"],
        "deadline": "2027-05-13",
        "priority": 2,
        "description": "Contract specifying purpose, security obligations, and deletion requirements.",
    },
    {
        "id": "processor_oversight",
        "title": "Oversight and monitoring of Data Processors",
        "category": "Processors & transfers",
        "act_sections": ["Section 8(2)"],
        "rule_references": ["Rule 6", "Rule 12"],
        "deadline": "2027-05-13",
        "priority": 2,
        "description": "Reasonable steps to ensure processors comply with security and processing obligations.",
    },
    {
        "id": "cross_border_transfer",
        "title": "Cross-border transfer compliance",
        "category": "Processors & transfers",
        "act_sections": ["Section 16"],
        "rule_references": ["Rule 15"],
        "deadline": "2027-05-13",
        "priority": 2,
        "description": "Transfers only to countries not restricted by Central Government notification.",
    },
    # --- Security ---
    {
        "id": "security_safeguards",
        "title": "Reasonable security safeguards",
        "category": "Security & breach",
        "act_sections": ["Section 8(5)"],
        "rule_references": ["Rule 12"],
        "deadline": "2027-05-13",
        "priority": 1,
        "description": "Encryption, access controls, logging, backups, and organisational measures.",
    },
    {
        "id": "security_logging",
        "title": "Access logging and one-year log retention",
        "category": "Security & breach",
        "act_sections": ["Section 8(5)"],
        "rule_references": ["Rule 12"],
        "deadline": "2027-05-13",
        "priority": 2,
        "description": "Logs retained for at least one year to detect unauthorised access.",
    },
    {
        "id": "breach_response_plan",
        "title": "Personal data breach response plan",
        "category": "Security & breach",
        "act_sections": ["Section 8(6)"],
        "rule_references": ["Rule 13"],
        "deadline": "2027-05-13",
        "priority": 1,
        "description": "Documented plan for detecting, containing, and responding to breaches.",
    },
    {
        "id": "breach_notify_board",
        "title": "Breach notification to Data Protection Board",
        "category": "Security & breach",
        "act_sections": ["Section 8(6)"],
        "rule_references": ["Rule 13"],
        "deadline": "2027-05-13",
        "priority": 1,
        "description": "Notify Board without undue delay; detailed report within 72 hours.",
    },
    {
        "id": "breach_notify_principals",
        "title": "Breach notification to affected Data Principals",
        "category": "Security & breach",
        "act_sections": ["Section 8(6)"],
        "rule_references": ["Rule 13"],
        "deadline": "2027-05-13",
        "priority": 1,
        "description": "Inform affected individuals in clear language about breach, impact, and remedial steps.",
    },
    # --- Children's data ---
    {
        "id": "children_verifiable_consent",
        "title": "Verifiable parental/guardian consent for children",
        "category": "Children's data",
        "act_sections": ["Section 9"],
        "rule_references": ["Rule 10", "Fourth Schedule"],
        "deadline": "2027-05-13",
        "priority": 1,
        "description": "Verifiable consent before processing personal data of children under 18.",
    },
    {
        "id": "children_no_harmful_tracking",
        "title": "No behavioural tracking or targeted advertising to children",
        "category": "Children's data",
        "act_sections": ["Section 9"],
        "rule_references": ["Rule 10"],
        "deadline": "2027-05-13",
        "priority": 1,
        "description": "Prohibition on tracking, behavioural monitoring, or targeted ads directed at children.",
    },
    # --- Significant Data Fiduciary ---
    {
        "id": "sdf_assessment",
        "title": "Significant Data Fiduciary (SDF) designation assessment",
        "category": "Significant Data Fiduciary",
        "act_sections": ["Section 10"],
        "rule_references": ["Rule 11"],
        "deadline": "2027-05-13",
        "priority": 3,
        "description": "Assess whether government may designate you as SDF based on volume, sensitivity, and risk.",
    },
    {
        "id": "sdf_dpo_appointment",
        "title": "Data Protection Officer appointment (if SDF)",
        "category": "Significant Data Fiduciary",
        "act_sections": ["Section 10"],
        "rule_references": ["Rule 11", "Rule 14"],
        "deadline": "2027-05-13",
        "priority": 3,
        "description": "SDF must appoint DPO based in India with prescribed qualifications.",
    },
    {
        "id": "sdf_dpia",
        "title": "Data Protection Impact Assessment (if SDF)",
        "category": "Significant Data Fiduciary",
        "act_sections": ["Section 10"],
        "rule_references": ["Rule 11"],
        "deadline": "2027-05-13",
        "priority": 3,
        "description": "SDF must conduct periodic DPIA for processing with risk to Data Principals.",
    },
    {
        "id": "sdf_audit",
        "title": "Annual data protection audit (if SDF)",
        "category": "Significant Data Fiduciary",
        "act_sections": ["Section 10"],
        "rule_references": ["Rule 11"],
        "deadline": "2027-05-13",
        "priority": 3,
        "description": "SDF must have annual audit by independent auditor.",
    },
    # --- Employment & special cases ---
    {
        "id": "employee_data_safeguards",
        "title": "Employee personal data safeguards",
        "category": "Employment & special cases",
        "act_sections": ["Section 7(c)", "Section 8"],
        "rule_references": ["Rule 5"],
        "deadline": "2027-05-13",
        "priority": 2,
        "description": "Safeguards for employee data processed under legitimate use for employment purposes.",
    },
    {
        "id": "cctv_processing",
        "title": "CCTV / video surveillance compliance",
        "category": "Employment & special cases",
        "act_sections": ["Section 4", "Section 5", "Section 7"],
        "rule_references": ["Rule 3"],
        "deadline": "2027-05-13",
        "priority": 2,
        "description": "Notice and lawful basis for CCTV footage capturing identifiable individuals.",
    },
]

OBLIGATION_SOURCE_MAP: dict[str, list[str]] = {
    ob["id"]: ["dpdp_act_2023", "dpdp_rules_2025"] for ob in OBLIGATIONS
}
# Enrich specific mappings
OBLIGATION_SOURCE_MAP.update({
    "breach_notify_board": ["dpdp_act_2023", "dpdp_rules_2025", "pib_rules_summary_2025"],
    "breach_notify_principals": ["dpdp_act_2023", "dpdp_rules_2025", "pib_rules_summary_2025"],
    "sdf_assessment": ["dpdp_act_2023", "dpdp_rules_2025", "dsci_rules_index_2025"],
    "sdf_dpo_appointment": ["dpdp_act_2023", "dpdp_rules_2025", "dsci_rules_index_2025"],
    "consent_manager_readiness": ["dpdp_rules_2025", "pib_rules_summary_2025"],
})
